name: "Deployment Workflow"
on:
    push:
        branches:
            - master
jobs:
    simple_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout repo"
          uses: actions/checkout@v2

        - name: "Build the image"
          run: |
            sudo docker build -t adebisibiola/books-app:1 .

        - name: "Login to Dockerhub"
          uses: docker/login-action@v1
          with:
            username: ${{ Secrets.DOCKERHUB.USERNAME }}
            password: ${{ Secrets.DOCKERHUB.PASSWORD }}

        - name: "Push image to Dockerhub"
          run: |
            docker push adebisibiola/books-app:1