name: "Deployment Workflow"
on:
    push:
        branches:
            - master
jobs:
    simple_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout repo"
          uses: actions/checkout@v2

        - name: "Build the image"
          run: |
            sudo docker build -t adebisibiola/books-app:2 .

        - name: "Login to Dockerhub"
          uses: docker/login-action@v1
          with:
            username: adebisibiola
            password: funkade0956

        - name: "Push image to Dockerhub"
          run: |
            docker push adebisibiola/books-app:2